version: '3'
services: 
    webserver:
        image: nginx:alpine
        container_name: slider-svelte
        restart: unless-stopped
        ports:
          - "5001:80"
        volumes:
          - ./:/usr/src/slider
          - ./nginx.conf:/etc/nginx/conf.d/nginx.conf